### ISSUE TITLE
build fails due to missing "TensorflowExtraction.h"

### ISSUE THREAD

**Issue by bis014** [Foxpace/BeSafeBox_Android_app#1]
> Task :mobile:externalNativeBuildDebug FAILED
Build native-lib_armeabi-v7a
ninja: Entering directory `C:\source\repos\BeSafeBox_Android_app\mobile\.cxx\cmake\debug\armeabi-v7a'
[1/5] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/calculations/nn/KerasSequentialModel.cpp.o
FAILED: CMakeFiles/native-lib.dir/src/main/cpp/calculations/nn/KerasSequentialModel.cpp.o 
C:\AppData\Local\Android\Sdk\ndk\21.1.6352462\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi19 --gcc-toolchain=C:/Users/BIS014/AppData/Local/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/BIS014/AppData/Local/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -Dnative_lib_EXPORTS -I../../../../src/main/cpp/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/calculations/nn/KerasSequentialModel.cpp.o -MF CMakeFiles\native-lib.dir\src\main\cpp\calculations\nn\KerasSequentialModel.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/calculations/nn/KerasSequentialModel.cpp.o -c ../../../../src/main/cpp/calculations/nn/KerasSequentialModel.cpp
../../../../src/main/cpp/calculations/nn/KerasSequentialModel.cpp:5:10: fatal error: 'TensorflowExtraction.h' file not found
#include "TensorflowExtraction.h"

**Comment by Foxpace** [comment]
For reference go to:  #3
