### ISSUE TITLE
our project BeSafeBox_Android_app lack org.apache.spark.ml.classification.RandomForestClassifier and TensorflowExtraction.h and motionapps.besafebox.ml.Model3100  ，Three file 。

### ISSUE THREAD

**Issue by wy1981105** [Foxpace/BeSafeBox_Android_app#3]
Hello!
   Your project BeSafeBox_Android_app lack org.apache.spark.ml.classification.RandomForestClassifier and TensorflowExtraction.h and motionapps.besafebox.ml.Model3100  ，Three file 。
   android studio4.0  Compilation failed.
   if you have  Three file，please provide.
   thanks,thans.

**Comment by Anshumansengar** [comment]
Any update did you get these 3 files?

**Comment by splitice** [comment]
I too confirm that these files are missing. Unfortunately this makes it very hard to verify the accuracy of this research.

**Comment by Foxpace** [comment]
Hi all, 
files were left out intentionally. The data were recorded under the agreement that they should not be publicly available and used only for this research. Models are created by the data given by the volunteers as they are direct interpretations of them, so they cannot be public too. I was not given consent to share them, and I must respect that.

I encourage you to take this project as a template/inspiration for your research or projects. 

For measuring data you can use my other project:
https://play.google.com/store/apps/details?id=motionapps.sensorbox&hl=en_US

You can follow this series for more information:
https://tomas-repcik.medium.com/list/fall-detection-android-app-besafebox-51b711742fa2
